---
version: '2'

services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg-schema-migration-test
  test:
    command: tail -f /dev/null
    image: pg-schema-migration:test
    working_dir: /opt/test
    volumes:
      - ${PWD}:/opt/test
    links:
      - pg
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@pg:5432/pg-schema-migration-test"
